# Generated by Django 3.1.7 on 2021-03-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20210313_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url_chrome_store',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url_github',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_github', models.CharField(blank=True, max_length=255, verbose_name='GitHub URL')),
                ('url_chrome_store', models.CharField(blank=True, max_length=255, verbose_name='GoogleChrome URL')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cms.article', verbose_name='記事')),
            ],
        ),
    ]
