# Generated by Django 3.1.7 on 2021-03-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210314_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cms.article', unique=True, verbose_name='記事'),
        ),
    ]
