# Generated by Django 3.1.7 on 2021-03-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20210314_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cms.article', verbose_name='記事'),
        ),
    ]
