# Generated by Django 3.1.7 on 2021-03-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20210314_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_firefox_addons',
            field=models.CharField(blank=True, max_length=255, verbose_name='Firefox ADD-ONS URL'),
        ),
    ]
