# Generated by Django 3.1.7 on 2021-03-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_product_url_firefox_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_pypi',
            field=models.CharField(blank=True, max_length=255, verbose_name='PyPI'),
        ),
    ]
