# Generated by Django 3.1.7 on 2021-03-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_product_url_pypi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_product',
            field=models.CharField(blank=True, max_length=255, verbose_name='Product URL'),
        ),
    ]
