# Generated by Django 3.1.7 on 2021-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_product_url_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_document',
            field=models.CharField(blank=True, max_length=255, verbose_name='Document URL'),
        ),
    ]
