# Generated by Django 3.1.7 on 2021-03-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_product_url_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_android',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Play URL'),
        ),
    ]
