# Generated by Django 3.1.7 on 2021-03-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_product_url_android'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ名')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag_list',
            field=models.ManyToManyField(to='cms.Tag'),
        ),
    ]
