# Generated by Django 3.1.7 on 2021-03-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20210321_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag_list',
            field=models.ManyToManyField(related_name='article', to='cms.Tag'),
        ),
    ]
