# Generated by Django 3.1.7 on 2021-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20210321_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
