# Generated by Django 3.1.7 on 2021-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20210326_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='priority_rank',
            field=models.IntegerField(default=255, verbose_name='優先順位'),
        ),
    ]
