# Generated by Django 3.1.7 on 2021-03-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_chrome_store',
            field=models.CharField(blank=True, max_length=255, verbose_name='GoogleChrome URL'),
        ),
    ]
