# Generated by Django 3.1.7 on 2021-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_article_url_chrome_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, verbose_name='本文'),
        ),
    ]
